require 'open-uri'
require 'json'
require 'net/http'
require_relative '../app/models/genre.rb'
require_relative '../app/models/movie.rb'
require_relative '../app/models/user.rb'
require_relative '../app/models/library.rb'
require_relative '../app/models/omdb_api.rb'
